CustomParam = ""

[Logger]
FileName = "./driver.log"
LogLevel = "INFO"

[Clients]
[Clients.Core]
Address = "127.0.0.1:57081"
UseTLS = false
CertFilePath = ""
ClientId = ""
Username = ""
Password = ""

[Service]
ID = "07383748"
Name = "MQTT协议驱动-07383748"
Activated = false
[Service.Server]
Address = "0.0.0.0:41372"
UseTLS = false
CertFile = ""
KeyFile = ""