CustomParam = ""

[Logger]
FileName = "./driver.log"
LogLevel = "INFO"

[Clients]
[Clients.Core]
Address = "demo.winc-link.com:57081"
UseTLS = false
CertFilePath = ""
ClientId = ""
Username = ""
Password = ""

[Service]
ID = "37471183"
Name = "MQTT协议驱动-37471183"
Activated = false
[Service.Server]
Address = "0.0.0.0:41372"
UseTLS = false
CertFile = ""
KeyFile = ""